<a href="https://colab.research.google.com/github/VicoSan07/AprendizajeAutomatico/blob/main/Tarea02_AA_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tarea 02 - Preprocesamiento en Python**

[Victor Sanchez](https://github.com/VicoSan07) <br>
Dataset: [Wine Quality](https://archive.ics.uci.edu/ml/datasets/wine+quality)

### **Carga de Datasets**

In [ ]:
#Para cargar los datasets a Google Colab
from google.colab import files
files.upload()

In [42]:
#Pandas es una librería especializada en el manejo y análisis de datos
import pandas as pd

#Carga de dataset 'vino rojo' 
dfwiner = pd.read_csv(r'winequality-red.csv',delimiter=";",
                      #Tipo de datos en cada columna
                      dtype={
                          'fixed acidity': float,
                          'volatile acidity': float,
                          'citric acid': float,
                          'residual sugar': float,
                          'chlorides': float,
                          'free sulfur dioxide': float,
                          'total sulfur dioxide': float,
                          'density': float,
                          'pH': float,
                          'sulphates': float,
                          'alcohol': float,
                          'quality': int,
                      })

#Carga de dataset 'vino blanco' 
dfwinew = pd.read_csv(r'winequality-white.csv',delimiter=";",
                      #Tipo de datos en cada columna
                      dtype={
                          'fixed acidity': float,
                          'volatile acidity': float,
                          'citric acid': float,
                          'residual sugar': float,
                          'chlorides': float,
                          'free sulfur dioxide': float,
                          'total sulfur dioxide': float,
                          'density': float,
                          'pH': float,
                          'sulphates': float,
                          'alcohol': float,
                          'quality': int,
                      })

dfwinew

                                                            fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
7.0 0.27 0.36 20.7 0.045 45.0 170.0 1.00100 3.00 0.45 8.8                                                   6
6.3 0.30 0.34 1.6  0.049 14.0 132.0 0.99400 3.30 0.49 9.5                                                   6
8.1 0.28 0.40 6.9  0.050 30.0 97.0  0.99510 3.26 0.44 10.1                                                  6
7.2 0.23 0.32 8.5  0.058 47.0 186.0 0.99560 3.19 0.40 9.9                                                   6
                                                      9.9                                                   6
...                                                                                                       ...
6.2 0.21 0.29 1.6  0.039 24.0 92.0  0.99114 3.27 0.50 11.2                                                  6
6.6 0.32 0.36 8.0  0.047 57.0 168.0 0.99490 3.15 0.46 9.6                                                   5
6.5 0.24 0.19 1.2  0.041 30.0 111.0 0.99254 2.99 0.46 9.4                                                   6
5.5 0.29 0.30 1.1  0.022 20.0 110.0 0.98869 3.34 0.38 12.8                                                  7
6.0 0.21 0.38 0.8  0.020 22.0 98.0  0.98941 3.26 0.32 11.8                                                  6

[4898 rows x 1 columns]

### **Manipulación de datos**

Nuestro principal objetivo será unificar ambos datasets en uno solo, para ello, crearemos una columna adicional en el que identifiquemos el tipo de vino con el que se trabaja: blanco o rojo 🍷

In [9]:
# Crear columnas con string constante en cada fila
dfwiner['type']='red'
dfwinew['type']='white'

In [11]:
# Visualización del resultado
dfwiner[["quality", "type"]].head()

   quality type
0        5  red
1        5  red
2        5  red
3        6  red
4        5  red

In [15]:
# Concatenar los dos datasets en uno solo
#dfwineall = pd.concat([dfwiner,dfwinew])
#dfwineall.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type,"fixed acidity;""volatile acidity"";""citric acid"";""residual sugar"";""chlorides"";""free sulfur dioxide"";""total sulfur dioxide"";""density"";""pH"";""sulphates"";""alcohol"";""quality"""
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0,red,NaN
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5.0,red,NaN
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5.0,red,NaN
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6.0,red,NaN
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0,red,NaN